### PR TITLE
Make the testimonials into a carousel

### PR DESCRIPTION
**Pull request by davidfischer**
The testimonials are in a carousel. There's a bunch of [options](https://flickity.metafizzy.co/options) but I made a few choices:

- I have it autoscrolling with the default 3s interval (we can force users to scroll manually or autoscroll at a different interval)
- We have buttons to scroll (these can be styled or removed)
- There's the dots at the bottom to indicate how many (this can be turned off)
- The width of scrolling items is configurable. I went with 75% of screen size at big screen sizes.

Before I start refactoring which testimonials to show, I wanted to get some feedback on this so far.

## Screenshot
Screenshot from 2024-07-17 15-38-55

### CODE REVIEW

**Comment by ericholscher** [comment]
This seems like a reasonable approach. It lets us highlight the "best" one, and folks can scroll around if they want to see more. :+1:

**Comment by davidfischer** [comment]
> I'd probably increase this, or just make it manual scroll?

I just tested this with 1.5s and it was way too fast. However, I'll push a commit with the variable so we can customize it later if we want to.

**Comment by ericholscher** [comment]
I meant slower, not faster. But I think manual is probably the best option for now, since auto-advancing is pretty annoying if you're actually trying to read it.

**Comment by davidfischer** [comment]
I did a PR to make it manually scroll: https://github.com/readthedocs/ethicalads.io/pull/444

**Pull request merged**
