### PR TITLE
Improve the UX of the similar pages page

### PR DESCRIPTION
**Pull request by davidfischer**
- Add loading indicator
- I think favicons will work better than opengraph images. There's some risk but not much to loading favicons (mostly SVGs).
- Update the URL when the form is submitted
- Some error handling
- ~~Currently the data is faked until the API is updated~~

### CODE REVIEW

**Review by ericholscher — COMMENTED** [review]
Looks good. Need to update the backend to parse the opengraph data, but that shouldn't be hard.

**Comment by davidfischer** [comment]
> Need to update the backend to parse the opengraph data, but that shouldn't be hard.

I think we can just grab the domain and append `favicon.ico` as a start. Favicons will probably be even better than opengraph data.

**Comment by ericholscher** [comment]
Ya, I meant description as well, but already solved that problem :)

**Review by ericholscher — APPROVED** [review]
Excited with the UX improvements here. Getting closer to something we can start showing 💯 

I imagine a similar page that hits the `similar-ads` API would be pretty easy to do. Could even maybe do it as another PR to this page and just have a button to choose if you want matching ads or pages 🤔

**Comment by davidfischer** [comment]
I updated this to show the distance if it's available from the API. Let's merge this after the backend is deployed

**Pull request merged**
