### PR TITLE
Initial book club blog post

### PR DESCRIPTION
**Pull request by ericholscher**
This intro could use a bit of love,
but here's a first draft.

### CODE REVIEW

**Review by davidfischer — APPROVED** [review]
This looks great. For a rough draft, I actually think it's pretty close to being mergeable.

**Comment by ericholscher** [comment]
This is mostly just waiting on our blog calendar to clear up. Got posts backlogged! 🎉

**Comment by davidfischer** [comment]
I say we aim to ship this tomorrow.

**Comment by ericholscher** [comment]
@davidfischer sounds good!

**Pull request merged**
