### PR TITLE
Add a reporting landing page

### PR DESCRIPTION
**Pull request by davidfischer**
The page seems a bit minimal, but I think that might be OK.

## Screenshot

Screenshot 2022-12-16 at 15-41-28 Transparent Reporting for your Ad Campaign

### CODE REVIEW

**Review by ericholscher — COMMENTED** [review]
This feels a little bit too much like a landing page, and not something that informs users. I was imagining something that had the full listing of reports that we offer, something closer to a reference than a marketing page. I don't think anyone will be hitting this page in SEO or about to convert on the inbound form, but it's mostly about answering questions in the sales process and learning more. Perhaps something in the Learning Hub over a landing page? 

I'm imagining the top info being:

* What reports are available, along with the fields in the reports. Probably something like this: https://www.ethicalads.io/publishers/faq/#what-data-can-i-see-about-the-ads for advertisers?
* What functionality do they have? (Exports, filtering?)
* How do I use them?

I think the video helps answer most of this, but the page obscures this information a bit more than I think is useful.

**Comment by davidfischer** [comment]
We could tweak the "detailed performance" and "transparency" section to have a small blurb on each report. Then the questions section could discuss how every report can be filtered by any time range and all of them can be exported.

**Comment by davidfischer** [comment]
I updated the FAQ section with details about the reports and data available.

**Review by ericholscher — APPROVED** [review]
Should we be linking this from somewhere in nav? At least in the footer perhaps?

**Comment by davidfischer** [comment]
I don't think it needs to be in the navigation. It's linked from the relevant section on the advertiser landing page and from the FAQ. Maybe an additional link from some places in the Learning Hub, but I think it's good.

**Pull request merged**
